extends:
  eslint-config-riot

parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'

rules:
  fp/no-mutating-methods: false
  fp/no-let: false
  fp/no-loops: false
  fp/no-delete: false
  fp/no-rest-parameters: false